### ISSUE TITLE
Quadro de Interesse

### ISSUE THREAD

**Issue by bernardohrl** [fga-eps-mds/2018.2-Grupo1#4]
Fazer um quadro que apresente possíveis tecnologias, para que todos os integrantes de MDS possam mostrar as tecnologias que estão interessados em utilizar.

**Comment by MarianaPicolo** [comment]
![interesses](https://user-images.githubusercontent.com/26073710/44939376-06a66f00-ad5b-11e8-9c54-aae0ef8b499a.png)
